### ISSUE TITLE
MakeMKV Not Updating

### ISSUE THREAD

**Issue by linxchaos** [rix1337/docker-ripper#10]
Hello! Just letting you know that the MakeMKV hasn't updated again. I can use the install.sh to fix that, but it isn't doing that automatically, nor when I delete the image and redownload.

**Comment by rix1337** [comment]
Its actually not supposed to auto update. Just the new key is fetched .

Ill trigger a new build.

**Comment by rix1337** [comment]
The automated build is only triggered if one of a few official makemkv images is built.

This has not yet happened, so I triggered a manual build on docker hub.

Thanks for the report .
