### ISSUE TITLE
No Progress when Ripping Specific Tracks 

### ISSUE THREAD

**Issue by jeprecated** [rix1337/docker-ripper#101]
``` 
--
outputting to //abcde.d8119510/track11.wav
 
to sector 215097 (track 11 [6:54.73])
Ripping from sector 183974 (track 11 [0:00.00])
```

It just hangs here for hours. I left it overnight and nothing :man_shrugging: Same disk, same track, each time.

I understand you don't give support to non-sponsors. **My only question is: how can I help myself here?** There is no entry in the logs (in the GUI or the actual log files). Is there some other log file I should take a look at? What should I do?

**Comment by jeprecated** [comment]
:face_exhaling: Yes I read it, as I commented. Didn't know that header was required.

**Comment by rix1337** [comment]
Yup, that's what the bot is here for.

You are describing an issue with either abcde or your specific disk.

I would start troubleshooting by trying to rip that CD with another tool on your desktop os, to confirm the disk is rippable. If that's the case open an issue at abcde
