### ISSUE TITLE
Help with knowing when a rip is complete

### ISSUE THREAD

**Issue by GLaDOS-lab** [rix1337/docker-ripper#106]
Have you read and understood this [part of the readme](https://github.com/rix1337/docker-ripper#do-you-offer-support)?

[X] YES

[] NO

### Issue description:
This is probably a very stupid question, but I was wondering if there was a way to show a progress bar, for example, or send a notification when complete so that I know to switch out the DVDs. This has been immensely helpful so far <3

**Comment by rix1337** [comment]
You can edit the script any way you like to achieve notifications
