### ISSUE TITLE
Empty ID3 tag on MP3 files

### ISSUE THREAD

**Issue by ThirtySomething** [rix1337/docker-ripper#107]
Have you read and understood this [part of the readme](https://github.com/rix1337/docker-ripper#do-you-offer-support)?

[X] YES

[ ] NO

### Issue description:

eye3d will write [no ID3 tag](https://abcde.einval.com/bugzilla/show_bug.cgi?id=72) in case the genre number is 255. Which version of eye3d is used in this project? Is there a way to use [mutagen](https://github.com/quodlibet/mutagen/blob/main/docs/api/id3.rst) instead of eye3d?

**Comment by rix1337** [comment]
You can access the build logs in the actions tab
https://github.com/rix1337/docker-ripper/actions

Specific version info might be listed there.

If alternative tools work well for you, feel free to send a pull request!
