### ISSUE TITLE
if eject is disabled, ripper continuously rips the same disk over and over again

### ISSUE THREAD

**Issue by ghost** [rix1337/docker-ripper#124]
Have you read and understood this [part of the readme](https://github.com/rix1337/docker-ripper#do-you-offer-support)?

[X] YES

[] NO

### Issue description:
if eject is disabled, ripper will continue to see that there is a disk in the drive and try ripping it again and again even if the first rip was sucessful

**Comment by ghost** [comment]
I should point out that if you are putting support and feature requests behind a paywall it will be harder to attract new users who can eventually become donors or sponsors.

**Comment by rix1337** [comment]
This is indeed not a business case, but meant to discourage people from asking for help.

I am however very open for PRs, so thanks for implementing and sending a fix 🤓
