### ISSUE TITLE
Output file path funky...

### ISSUE THREAD

**Issue by agster27** [rix1337/docker-ripper#13]
Hello!

First of all I was about to give up looking for an automated ripping process and try to build my own. Then I ran across yours. This is great.

So I am running this Docker on a Synology NAS. It is working! However...

The path it saves a DVD to is malformed.

/incoming/Ripper/DVD/","/dev/sg5" DRV:0,2,999,1,"BD-ROM ASUS BC-12D2HT 3.01","DUNE_DISC1

The only thing I changed was in the ripper.sh
`DRIVE="/dev/sg5"`

Any assistance is appreciated.

**Comment by agster27** [comment]
So I spoke too soon. After it was done the script nicely cleaned everything up and put the finished file in "finished".

However it still seems the temp directory name is wrong.  

Great Docker! Going to see how I can contribute.

**Comment by rix1337** [comment]
Please elaborate. I do not understand the issue

Is there a whitespace / character issue with the output dir?

**Comment by agster27** [comment]
> Please elaborate. I do not understand the issue
> 
> Is there a whitespace / character issue with the output dir?

No. If this is expected then it's not an issue. It just looked odd to me and I figured I would report it :)

**Comment by rix1337** [comment]
I still don't understand what is the issue, could you try to reword it? 

Sounds like you solved it, so I will close this for now

**Comment by rix1337** [comment]
But thank you for posting the issue

**Comment by agster27** [comment]
> I still don't understand what is the issue, could you try to reword it?
> 
> Sounds like you solved it, so I will close this for now

There was no real issue. The path just looked odd and I reported it as I was not sure if that was expected. Thanks!
