### ISSUE TITLE
Infinite loop caused by unexpected makemkvcon output

### ISSUE THREAD

**Issue by wilddeej** [rix1337/docker-ripper#14]
I ran into some trouble running docker-ripper, due to the unexpected output from `makemkvcon`.  Specifically the command `makemkvcon -r --cache=1 info disc:9999 | grep DRV:0` returned the output:

`DRV:0,256,999,0,"","",""`

The code in `ripper.sh` has no checks for responses outside of the responses it is expecting, and so the while/do loop never finds what it's looking for and never exits.  Independent of the strange output from `makemkvcon` (another issue entirely, of course), `ripper.sh` should handle unexpected responses differently.

**Comment by rix1337** [comment]
Good request. If you can, please send a pull request. I will not be able to work on this until the end of February.

**Comment by wilddeej** [comment]
OK, I'll do that.
I was thinking about putting in a counter of sequential bad responses from makemkvcon, and once it reached some sort of threshold (tentatively 10) just bailing out of the script entirely.  That seem reasonable to you?

**Comment by rix1337** [comment]
I was thinking about a sort of "catch everything else" block, that will eject the disk with an "unknown type" error.

But either could work

**Comment by rix1337** [comment]
Thanks for the support.

**Comment by wilddeej** [comment]
You bet - thank YOU for such an excellent utility!

**Comment by wilddeej** [comment]
Epilog: I'm still trying to track down why `makemkvcon `doesn't work within the Docker container.  I've built it locally on my Ubuntu 16.04 system using your `install.sh`, and it works there, but not within a container I start from that same system.  Even stranger, I can run the `ripit` command just fine within the same Docker container!

As it turns out, all that was needed was another parameter to the docker container start-up.  I tracked this down with the `lsscsi` command:
```
  # lsscsi -g
  [2:0:0:0]    disk    ATA      ST3500630AS      E     /dev/sda   /dev/sg0
  [3:0:0:0]    cd/dvd  HL-DT-ST BD-RE  BH16NS40  1.00  /dev/sr0   /dev/sg1
  [7:0:0:0]    disk    ATA      ST3500320AS      SD04  /dev/sdb   /dev/sg2
```

Since two devices are listed for `cd/dvd`, that seems to mean that both devices need to be passed on to the container too, so using your startup command with an additional argument of `--device=/dev/sg1:/dev/sg1` took care of it!

It might be good to add this to the `README.md` file, to help other poor souls who run into similar issues... your call.
