### ISSUE TITLE
Allow alternate ripping commands for BluRay, DVD, CD, Data-Disk ripping

### ISSUE THREAD

**Issue by wilddeej** [rix1337/docker-ripper#16]
The `ripper.sh` script already contains commands to rip disks of type BluRay, DVD, CD, and Data-Disk, but it would be a useful enhancement to allow an easy mechanism for substituting these commands.  As an example, when ripping a CD audio disk, I would prefer to only produce MP3 files at a bit rate of 192K.  While it is absolutely possible to customize the `ripper.sh` script to change this behavior, another way to accomplish this same action would be for `ripper.sh` to check for the existence of a `CDrip.sh` script in the same directory, and if found, execute that script with appropriate parameters to replace the `ripper.sh` script operation.

**Comment by rix1337** [comment]
Please send a PR if viable.
