### ISSUE TITLE
Does not detect usb drive when running in osx

### ISSUE THREAD

**Issue by tim1234567890804** [rix1337/docker-ripper#20]
I've got a USB bluray drive, when I plug drop a bluray disk into the drive the docker container does not detect any changes. Can the readme give an example of how to use this with OSX and/or a usb drive.

**Comment by rix1337** [comment]
I cannot help with hardware issues. This is something for the docker devs.

**Comment by tim-baker115** [comment]
The docker run would need a change, e.g /dev/sr0 would be /dev/disk1 or something similar. 

I'll knock something up which detects the OS and changes the docker run command depending on OS and device specific availability. Linux would have the same problem for usb blurays drives. This is NOT a hardware "issue".

I think the readme would also benefit massively from allowing for multiple cdrom drives (you've even got a link to someone who's achieved this). Have multiple docker instances each looking at a different /dev/ perhaps.
