### ISSUE TITLE
Permissions are not set if moving file

### ISSUE THREAD

**Issue by aron7676** [rix1337/docker-ripper#21]
If I am reading it right, if writing to a different finish directory, the file's permissions are not updated. Should the permissions fix not come before the move function? 
Current code:
```
if [ "$SEPARATERAWFINISH" = 'true' ]; then
    DVDFINISH="$STORAGE_DVD"/finished/
    mv -v "$DVDPATH" "$DVDFINISH" 
 fi
 echo "$(date "+%d.%m.%Y %T") : Done! Ejecting Disk"
 eject $DRIVE >> $LOGFILE 2>&1
 # permissions
 chown -R nobody:users "$STORAGE_DVD" && chmod -R g+rw "$STORAGE_DVD"
fi

```
Suggested fix:
```
# permissions
 chown -R nobody:users "$STORAGE_DVD" && chmod -R g+rw "$STORAGE_DVD"

if [ "$SEPARATERAWFINISH" = 'true' ]; then
    DVDFINISH="$STORAGE_DVD"/finished/
    mv -v "$DVDPATH" "$DVDFINISH" 
 fi
 echo "$(date "+%d.%m.%Y %T") : Done! Ejecting Disk"
 eject $DRIVE >> $LOGFILE 2>&1

fi
```

Also able to not hold up the process, by putting & after mv command, right? 
My specific case I am copying to a network location, but ripping to a local SSD.

**Comment by rix1337** [comment]
https://github.com/rix1337/docker-ripper#how-do-i-set-ripper-to-do-something-else

Good issue, please send a pull request if you deem this mergable. I'll take a look if I find the time. 👍
