### ISSUE TITLE
MakeMKV Update

### ISSUE THREAD

**Issue by Lueddy11** [rix1337/docker-ripper#23]
"This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.","This application version is too old.  Please download the latest version at %1 or enter a registration key to continue using the current version.","http://www.makemkv.com/"

**Comment by rix1337** [comment]
Thanks for the info and reading https://github.com/rix1337/docker-ripper#makemkv-needs-an-update carefully. The automatic build failed again.. Update is being built manually.

**Comment by rix1337** [comment]
This usually takes up to 2 hours
