### ISSUE TITLE
Ripper won't eject 

### ISSUE THREAD

**Issue by Wolframpanzer** [rix1337/docker-ripper#25]
I've got a little problem where Ripper won't eject the Disk and keeps ripping in a endless loop.
The only thing that the Log says are the following lines:
eject: tried to use `devtmpfs' as device name but it is no block device

eject: unable to find or open device for: `/dev/sr0'

**Comment by rix1337** [comment]
Is it ripping at all? If not, you first need to make sure you are passing through your disk drive as /dev/sr0 (even if your host drive has another id, you need to pass it through internally as /dev/sr0)

If that does not help it seems your device is incompatible with the eject command.
Best you try and modify your local ripper.sh yourself with an alternative command, though I know of none.
This is one of the lines https://github.com/rix1337/docker-ripper/blob/a3470835533b126c305e4765edb879b2669aec7d/root/ripper/ripper.sh#L57

If there is a third party package required I will try and include it in the Dockerfile.

**Comment by Wolframpanzer** [comment]
Now after I tried a few commands it finally worked.
I just replaced "eject $DRIVE >> $LOGFILE 2>&1 "
With " eject /sr0 "

**Comment by rix1337** [comment]
If you pass through the drive as described in the README it should not be at /sr0 but instead at /dev/sr0 - but that does not matter:

I placed the ripper.sh outside the container intentionally, so these issues can be fixed on each users machine - glad you figured it out.
