### ISSUE TITLE
ripper.sh error in line 'cd $'

### ISSUE THREAD

**Issue by maker112358** [rix1337/docker-ripper#27]
Line 31 cd $ in ripper.sh generated the following error for me:

> 22.11.2019 20:04:23 : CD detected: Saving MP3 and FLAC
> 22.11.2019 20:17:07 : Done! Ejecting Disk
> /config/ripper.sh: line 31: cd: $: No such file or directory
> 22.11.2019 20:18:42 : CD detected: Saving MP3 and FLAC
> 22.11.2019 20:31:28 : Done! Ejecting Disk
> /config/ripper.sh: line 31: cd: $: No such file or directory

It would continue to re-rip the same CD indefinitely.
I changed back to the previous version of ripper.sh and it seemed to resolve the issue.

Hopefully this helps.

**Comment by micahfocht** [comment]
I fixed this in #29.
