### ISSUE TITLE
problem ejecting disc

### ISSUE THREAD

**Issue by blackbunt** [rix1337/docker-ripper#30]
Hi, after a successfull rip the disc won't be ejected.The logfile says:

16.01.2020 00:45:23 : Done! Ejecting Disk
/config/ripper.sh: line 31: cd: $: No such file or directory

after 60 s the script will again rip the same disc...

any ideas?

**Comment by Bilhix** [comment]
Hi 

I also have a similar issue with the dvd drive not ejecting, however log shows differently:

16.01.2020 13:22:27 : Done! Ejecting Disk
16.01.2020 13:23:34 : DVD detected: Saving MKV

Will continue to cycle as long as left unattended, am using a "MediaTek Inc. Samsung SE-208 Slim Portable DVD Writer" mounted via USB if that helps.

**Comment by blackbunt** [comment]
i figured something out: can cou go into the ripper containers bash and manually run "eject"
maybe the drive is not detected by the script.
i did a clean docker image installation and somethow it now works out of the box.

Another Question: I can't figure out how to use multiple drives to rip. I created multiple instances of the container and mapped the drives correctly. Folders for each output are diffferent.
But somehow the containers are mixed together.
MakeMKV rips only from the first Drive altough i mapped a other container to /dev/sr1

**Comment by rix1337** [comment]
There sadly is no alternative (to my knowledge) to the eject command. If ` eject $DRIVE` is not working from within your container or for your specific drive you will need to try and find a different drive or an alternative programm call to get this done.

Ripping multiple drives is as easy as running this image in multiple containers (one for each drive).

**Comment by blackbunt** [comment]
@rix1337 can i contact u somehow? i've got another question regarding your docker "verarbeitung"

**Comment by rix1337** [comment]
Go on https://gitter.im/RSScrawler/Lobby and open a private chat

**Comment by johncm** [comment]
`[rancher@rancher-octocore ~]# eject --help`
BusyBox v1.27.2 () multi-call binary.

Usage: eject [-t] [-T] [DEVICE]

Eject DEVICE or **default /dev/cdrom**

	-t	Close tray
	-T	Open/close tray (toggle)

(I know it is not the same version running in the container but the defaults are the same.)
Also, try specifying the device inside the container as /dev/cdrom, most distros link it also:
```
[root@rancher-octocore ~]# ls -l /dev/cd*
lrwxrwxrwx    1 root     root             3 Jan 28 22:52 /dev/cdrom -> sr0

```
@rix1337 - you may want to update the doc/README to show something like:
```
docker run -d \
  --name="Ripper" \
  -v /path/to/config/:/config:rw \
  -v /path/to/rips/:/out:rw \
  --device=/dev/sr0:/dev/cdrom \
  rix1337/docker-ripper
```
but I'm not sure how "makemkv" searches for devices...
A dual definition may even help:
```
  --device=/dev/sr0:/dev/cdrom \
  --device=/dev/sr0:/dev/sr0 \

```
Not sure if docker/docker-compose would complain...

**Comment by rix1337** [comment]
@johncm /dev/sr0 is the default optical drive on all systems I work with, no need to change the readme. Glad you found the different binding on your system 😃
