### ISSUE TITLE
Add option to select MakeMKV profile?

### ISSUE THREAD

**Issue by csandman** [rix1337/docker-ripper#32]
I have a proposal for a new feature which might be useful for some but I'm not exactly sure how one would accomplish this.  I use the [video transcoding](https://github.com/donmelton/video_transcoding) tool for trans-coding my movies after I've ripped them but one of the recomendations it has for ripping blurays is to use the FLAC profile when doing the initial MakeMKV rip as handbrake can handle FLAC audio better than DTS-HD.  Expanding on this, I was thinking it might make sense to offer this package with all of the default profiles that come with MakeMKV which I found [here](https://www.makemkv.com/forum/viewtopic.php?t=18366#p67460).  I also extracted all of the basic profiles and made a gist of them [here](https://gist.github.com/csandman/5638a54730869cf4addf3df43f7fc845).

I'm not sure if this is within the scope of what this project is meant to do, but it would be cool if you could add an environment variable or something like that for the profile (--profile=default|flac|aac-st|wdtv) and have that be used in the ripping process.  Or, if you don't want to go that far, you could always just include these profiles in the code and allow people to select them in their custom scripts.

I know this could always be added manually when adding a custom script but these profiles aren't necessarily the easiest to uncover and it might be nice to include them for people.  Let me know what you think!

**Comment by rix1337** [comment]
Good idea but out of scope of this. Could you provide examples?
