### ISSUE TITLE
Ripper container outdated

### ISSUE THREAD

**Issue by Waxyen** [rix1337/docker-ripper#33]
Thanks for creating and maintaining this awesome project! I have one question regarding the inner-workings of the image/container.

When there is a new version of docker-ripper, the software does not want to rip disks anymore until after the update. It gives an outdated message in the Ripper logs.

Is there a work-around for it? I used to use Vortexbox with about the same ripper software, which kept running for years (although updating was always a smart move of course). So I suspect that the software itself should be able to keep running, even if there is an update. I have got a valid and recent MakeMKV key.

I am asking this, because this container is running somewhere, where regularly downloading a new image (2GB) is not an option and I would love it, if the container keeps working for a longer period of time.

Many many thanks in advance!

**Comment by rix1337** [comment]
Have you supplied your valid MakeMKV key to the container? My understanding is, it would then continue running without an update. Have not tested, because I never bought a key myself.

**Comment by Waxyen** [comment]
Yes I have. Exactly according to the documentation provided.
I also see the container picking up the key on start. If I leave the key out, it tells me that there is no key found. So I think it's quite sure the key gets loaded.

I even tried different keys, because there are more available for me. Is there a check built-in, where it validates the key as far as you know?

**Comment by rix1337** [comment]
Hm,.. my container does none of that. The whole logic lies within makemkv. Does it output something like "licensed to XXX" when you start ripping? Might be nothing I can do.

**Comment by rix1337** [comment]
As long as MakeMKV picks up your license key and uses that one, I would expect it to work without forcing an update. Thats how I read their documentation.

**Comment by Waxyen** [comment]
```
ripper    | *** Running /etc/my_init.d/10_syslog-ng.init...
ripper    | Mar 23 09:20:55 f88bda130beb syslog-ng[8]: syslog-ng starting up; version='3.5.6'
ripper    | Mar 23 09:20:56 f88bda130beb syslog-ng[8]: EOF on control channel, closing connection;
ripper    | *** Running /etc/my_init.d/ripper.sh...
ripper    | Found settings.conf. Replacing beta key file.
ripper    | 23.03.2020 09:20:57 : Starting Ripper. Optical Discs will be detected and ripped within 60 seconds.
ripper    | 23.03.2020 09:20:59 : DVD detected: Saving MKV
```

This is the output on start. I can't pull an older version of docker-ripper, can I? Otherwise I'll have to wait until my current version gets outdated to continue testing with that.

**Comment by Waxyen** [comment]
Can I send you a MakeMKV key in private somewhere, if you're interested.

**Comment by rix1337** [comment]
We could go forward with you sending a key, but I would rather wait for another report when it gets outdated again @Waxyen

**Comment by Waxyen** [comment]
Yes, good idea. I am waiting for a new release to see if there are some logs that will help discover what goes on.

**Comment by rix1337** [comment]
Alright, if that does not happen in the foreseeable future, we can try something else.
I'll keep the issue open, its not like someone will rate me by issue resolve time 😜

**Comment by rix1337** [comment]
Due to not owning a key for MakeMKV I have never checked if this actually works

```
To add your purchased license key to MakeMKV/Ripper add it to the enter-your-key-then-rename-to.settings.conf at app_Key = "[ENTER KEY HERE]" and rename the file to settings.conf.
```

If its not, than your issue is understandable.

**Comment by rix1337** [comment]
Ill close this for now.

**Comment by Waxyen** [comment]
Sorry about not giving an update for a while. I did not change anything in my configs, but it remains working fine with newer versions released. I don't know what exactly broke it, of fixed it. I'll let you know if I encounter any other issues with it. Anyway, thanks for the help!

**Comment by rix1337** [comment]
Thats alright. I closed it just for inactivity..
