### ISSUE TITLE
MakeMKV optical drive --device /dev/sr0 --device /dev/sg2

### ISSUE THREAD

**Issue by sirKitKat** [rix1337/docker-ripper#36]
I have a MakeMKV Docker (jlesage/makemkv) running and the documentation of that docker states the following:

> An optical drive is represented by two Linux device files: /dev/srX
> and /dev/sgY. For optimal performance, the container needs both
> of them. So if your optical drive is represented by /dev/sr0 and
> /dev/sg2, you need to add
> --device /dev/sr0 --device /dev/sg2 to the Extra Parameters
> field.

I was wondering why this docker only requests /dev/sr0 and not /dev/sg2 ?

**Comment by rix1337** [comment]
People seem to have not experienced any issues running it that way.
