### ISSUE TITLE
AAC Support

### ISSUE THREAD

**Issue by mirineumark** [rix1337/docker-ripper#37]
I wanted to rip to AAC rather than MP3 or FLAC. I fiddled around with the CDrip.sh file, couldn't get it to work and finally realized you don't have the `faac` dependency installed. `ripit` already supports it. I think you just need the dependency in the Dockerfile. Any chance you could add that?

**Comment by rix1337** [comment]
Sure thing

**Comment by mirineumark** [comment]
So unfortunately that didn't work, but I did a few hours of research and figured out why. The version of faac you added doesn't have support for the MP4 library and so everything is failing (some stupid licensing thing). I tested a solution, that involves downloading the deb file here:
https://launchpad.net/ubuntu/bionic/amd64/faac/1.29.3+git20170724-1

and then just running
```bash
dpkg -i faac_1.29.3+git20170724-1_amd64.deb
```

After that, it just worked. I am going to attempt to open a PR. I'll get back to you on that.

**Comment by mirineumark** [comment]
So. A few hours later I got that to work but....turns out faac doesn’t actually output files Apple (Apple Music, QuickTime, et cetera)....so time for a new approach. 

Turns out you can build compatible AAC files with ffmpeg which you are already compiling. For some reason the final bin was still in the `/tmp/ffmpeg/bin` directory so I moved it to `/usr/bin` in the install script.

Secondly, ripit incorrectly used the `author` metadata tag for the artist and Music wasn't recognizing that so I added a sed command to the install script to replace `author` with `artist`. It only occurs in the ffmpeg section so it shouldn't affect anywhere else in its code.

Third, for ffmpeg, I found out there's a better quality aac library for ffmpeg you can use rather than the built in one, but it needs to be installed as part of the compile. I wouldn't have tried it out except you were already compiling ffmpeg from source anyway so might as well give it a go. That's what I'm working on now. If its too much trouble and I can't get that part working I'll skip it but either way I should have PR up today.

**Comment by mirineumark** [comment]
Okay @rix1337 Got it all working. Take a look if you would. No rush. In the meantime I can use my fork.
https://github.com/rix1337/docker-ripper/pull/38
