### ISSUE TITLE
MakeMKV not updating to latest

### ISSUE THREAD

**Issue by ShoGinn** [rix1337/docker-ripper#4]
My Docker skills are newb at best.

But when I started up your docker, it seems like it is using an old image rather than using your install.sh

Mainly because your install.sh should update the makemkv to the latest version 1.10.8 as of today.

educate me if you would ;)

```
root@8fa7fc9a3b99:/# makemkvcon info
MakeMKV v1.10.7 linux(x64-release) started
The new version 1.10.8 is available for download at http://www.makemkv.com/download/
Use: makemkvcon [switches] Command [Parameters]
```

**Comment by rix1337** [comment]
I have triggered a current dockerfile build... seems my automated build on new versions has not triggered automatically..
