### ISSUE TITLE
Experience Using Ripper On Windows 10?

### ISSUE THREAD

**Issue by irtheman** [rix1337/docker-ripper#41]
I took the docker-compose.yml file and added Privileged: ON so it would see my DVD drive. No errors pop up but no ripping takes place either. Any suggestions on how to diagnose this?

Thanks!
Matthew Hanna

**Comment by rix1337** [comment]
What is the output of:
`makemkvcon -r --cache=1 info disc:9999 | grep DRV:0`

when you run it inside the container?

No idea if docker for windows is even able to pass through native windows devices, since afaik it is running on a slim linux vm.

To be fair, I deem it highly unlikely.

**Comment by irtheman** [comment]
True. I found the windows equivalent of /dev/sr0.
  device: class/{4d36e965-e325-11ce-bfc1-08002be10318}:/dev/sr0
makemkvcon gives me
  'DRV:0,1,999,0,"DVD-ROM Msft Virtual DVD-ROM 1.0","","/dev/sr0'
which I'm not sure is correct. Ripper actually dumped an ISO file I have never seen before without having a disc inserted. More research to come...

**Comment by rix1337** [comment]
Ill close this for now. Let me know, what you find out.
