### ISSUE TITLE
ccextractor errors in log. 

### ISSUE THREAD

**Issue by darsys** [rix1337/docker-ripper#42]
I am getting the following in the Ripper.log when I attempt to rip a dvd:
MSG:4040,0,1,"Unable to execute external program 'ccextractor' as its path is not set in preferences","Unable to execute external s its path is not set in preferences","ccextractor"

I was about to modify the clone the dockerfile and try to get ccextractor compiled on the image but wanted to make sure there wasn't a better solution out there.

**Comment by rix1337** [comment]
Thats the right way to go forward. You need to forrk this and add the tool.

What are you using it for? If its worthwhile send a PR and ill merge it!

**Comment by darsys** [comment]
I am  using ripper for backing up our dvd/blueray collection, along with home videos and some audio cds, if that is your question.  My understanding is that ccextractor is required for closed captions, which I would like to include.  I am a little unsure why I am the only one reporting an issue with it.  I will add the compiling in the install script since you already have the build tools installed.

**Comment by emmakat** [comment]
I have solved this in my forked version by adding this line to my settings.conf file (I have purchased a makemkv license, if that matters)

app_ccextractor = "/usr/local/bin/ccextractor"
