### ISSUE TITLE
Error "Invalid or incomplete multibyte or wide character"

### ISSUE THREAD

**Issue by lettore** [rix1337/docker-ripper#43]
Hello,
I'm Italian and I have a lot of errors ripping CD Audio of Italian artists.
In the log I see this error:`Cannot open specified output file /out/Ripper/CD/wav/Vasco Rossi/Vivere O Niente/01 Vivere Non �� Facile.rip: Invalid or incomplete multibyte or wide character`
The problem obviously are characters like à è ù ì etc... that are really used in Italian language.
I think I should enable some kind of language support in the base image, but it will be possible to edit the script to intercept those characters and replace them with a more friendly version without the accent?

**Comment by rix1337** [comment]
We would need a bash command to remove/ignore the unicode characters from ripper.sh.
Your system's encoding seems unable to handle the filenames.

**Comment by rix1337** [comment]
Closed for lack of external support
