### ISSUE TITLE
would getting coverart be out of scope?

### ISSUE THREAD

**Issue by emmakat** [rix1337/docker-ripper#47]
I was wondering if it would be useful (if I can figure out a PR for it), to try to get cover art for CDs?
Apparently in RipIt: 
--coverorg will enable coverart search at coverartarchive.org if MusicBrainz release ID is known (using MusicBrainz with option --mb).
--mb allows access to the MusicBrainz DB not using the cddb-protocoll (like in older versions) but using the perl module WebService::MusicBrainz. One needs the DiscID calculation tool, either the DiscID-command or in addition the perl module MusicBrainz::DiscID (recommended).

_Probably out of scope, but I wanted to inquire.__

**Comment by rix1337** [comment]
Sure, also we need to change ripit over to MusicBrainz since cddb seems to be gone for good. Would you be able to fix ripper.sh accordingly?

**Comment by emmakat** [comment]
yes I will try!

**Comment by rix1337** [comment]
Closed for inactivity
