### ISSUE TITLE
multi rip

### ISSUE THREAD

**Issue by MrTimn109** [rix1337/docker-ripper#49]
Hello, I'm looking to find a way to get this to rip multiple disks at one time. any thoughts? or should this work already? I'm running the docker on an unraid server. I tried running two docker containers but I was unsuccessful. I changed the values to be  /dev/sr1 and /dev/sr2 respectively.  in separate containers but it did not work for me what would have to happen to make this work?

**Comment by rix1337** [comment]
Read the readme on how to do this
