### ISSUE TITLE
Eject?

### ISSUE THREAD

**Issue by ShoGinn** [rix1337/docker-ripper#5]
How can we get eject working?

**Comment by ShoGinn** [comment]
made the container privileged and it works; just curious if you have a workaround for this?

**Comment by rix1337** [comment]
FYI: Privilege is required to access system devices,  I guess.. another hint was that the current eject method only works with sata devices... 

I'll investigate further, but since the whole script can easily be tweaked I dont think its really necessary.. (as long as makemvk is up2date)
