### ISSUE TITLE
Latest update giving library error.

### ISSUE THREAD

**Issue by James-Smart** [rix1337/docker-ripper#51]
Me again sorry, looks like the latest build is throwing the following:
10.08.2020 14:43:36 : Unexpected makemkvcon output:
rm: cannot remove '*.tmp': No such file or directory
**makemkvcon: error while loading shared libraries: libmakemkv.so.1: cannot open shared object file: No such file or directory**

It repeats several times before giving up:

10.08.2020 14:44:36 : Unexpected makemkvcon output:
10.08.2020 14:44:36 : Too many errors, ejecting disk and aborting
makemkvcon: error while loading shared libraries: libmakemkv.so.1: cannot open shared object file: No such file or directory

**Comment by rix1337** [comment]
Yup, there is a build error (that did not stop the build itself) which leads to ffmpeg. Hopefully updating to ffmpeg 4.3.1 fixes this

**Comment by James-Smart** [comment]
Just pulled the new build and that still complains about the same dependency FYI

**Comment by rix1337** [comment]
Currently no idea how to fix this. Any help is welcome.
