### ISSUE TITLE
You need to update to the latest version of makemkv

### ISSUE THREAD

**Issue by ViggoGaming** [rix1337/docker-ripper#53]
Hey!
I keep getting this error that says I have to update to the latest version of makemkv. In your README you say I just can open a issue and you will update it to the latest version :+1: 

**Logs:**
MSG:5075,131072,2,"The new version 1.15.3 is available for download at http://www.makemkv.com/download/","The new version %1 is available for download at %2","1.15.3","http://www.makemkv.com/download/"
Thanks in advance for the help!

**Comment by mervincm** [comment]
I built a new stack with this container and I am not experiencing this error. Maybe you can just refresh yours?

**Comment by rix1337** [comment]
I triggered the rebuild last night. Latest version should be up
