### ISSUE TITLE
Ripper Issue

### ISSUE THREAD

**Issue by Lobsi** [rix1337/docker-ripper#56]
Ihave already tried so much troubleshooting but Ripper not more working with Audio CD`s...
Every time ill get the following output:

*** Running /etc/my_init.d/ripper.sh...
Using MakeMKV beta key: OMG-I-accidentally-posted-my-license-and-edited-it-away-:)
12.10.2020 18:48:32 : Starting Ripper. Optical Discs will be detected and ripped within 60 seconds.
rm: cannot remove '*.tmp': No such file or directory
12.10.2020 18:48:47 : CD detected: Saving MP3 and FLAC

Environment is a Unraid Server with the latest "rix1337/docker-ripper" Docker Container who is available from Community applications... Is there another Version available somewhere who is working?

**Comment by rix1337** [comment]
You can simply ignore:
`rm: cannot remove '*.tmp': No such file or directory` this error is irrelevant if ripper has not created temp files yet.

This means we will not be able to help by just this log (there is nothing significant there)

You should try to run
`/usr/bin/ripit -d "$DRIVE" -c 0,2 -W -o "$STORAGE_CD" -b 320 --comment cddbid --playlist 0 -D '"$suffix/$artist/$album"'  --infolog "/log/autorip_"$LOGFILE"" -Z 2 -O y --uppercasefirst --nointeraction` manually within your container and fix any issues that are displayed there.

**Comment by Lobsi** [comment]
Hi rix1337,
thank you for your help, its very appreciated!
I have done your hint but it is not really working.

Ripper is now completely irritated:

*** Running /etc/my_init.d/ripper.sh...
*** Running /etc/my_init.d/ripper.sh...
Using MakeMKV beta key: "here-iy-my-valid-key-typed-in"
12.10.2020 19:39:43 : Starting Ripper. Optical Discs will be detected and ripped within 60 seconds.
rm: cannot remove '*.tmp': No such file or directory
12.10.2020 19:39:44 : Data-Disk detected: Saving ISO
12.10.2020 19:39:44 : Done! Ejecting Disk
12.10.2020 19:39:44 : Data-Disk detected: Saving ISO
12.10.2020 19:39:44 : Done! Ejecting Disk
rm: cannot remove '*.tmp': No such file or directory
12.10.2020 19:40:45 : CD detected: Saving MP3 and FLAC
12.10.2020 19:40:45 : CD detected: Saving MP3 and FLAC

Watching my target directory there is following created by ripper:

\Ripper\DATA\_BHCZG~J\dev\SQCGLN~V Folder who is empty

Do you have another idea what i could do?
The disc i have inserted is a Audio CD (Earth wind & fire - big hits & remixes)
and i have tried also other CDs...

regards

Lobsi

**Comment by Lobsi** [comment]
the console Output from your input is the following:

# /usr/bin/ripit -d "$DRIVE" -c 0,2 -W -o "$STORAGE_CD" -b 320 --comment cddbid --playlist 0 -D '"$suffix/$artist/$album"' --infolog "/log/autorip_"$LOGFILE"" -Z 2 -O y --uppercasefirst --nointeraction
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(\\%(?:\\=)?(\w|\\{ <-- HERE (?:\w|\\[^\w\\{}]|\\\\\\[\\{}])*\\}|\\\W))/ at /usr/share/perl5/MP3/Tag.pm line 2611.
Use of uninitialized value $ENV{"USER"} in string at /usr/bin/ripit line 349.



RipIT version 4.0.0_rc_20161009.
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.

cddb: checking for os ... Linux (x86_64) [little endian] [64 bit]


Process summary:
----------------
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.


Please insert an audio CD!

**Comment by rix1337** [comment]
The issue is with an upstream package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947756

**Comment by Lobsi** [comment]
Dear Rix,
Thank you for your analysis, but for me its unclear what i should do now?
Could i downgrade somehow the libmp3 version back to a working state?
How could i get ripper back in order to being able to rip a ton of old CD`s?

Thank you for further advices :)

best regards and stay healthy

Lobsi

**Comment by rix1337** [comment]
Nothing I or you could do right now... 
libmp3-tag-perl 1.15 fixes this and is not available for phusion baseimage right now.

**Comment by Lobsi** [comment]
Is there a way to circumvent this issue for now or have all people with this issue still to wait until it`s fixed?

**Comment by Lobsi** [comment]
i could live also for bulding a vm for your ripper, do you have any recommendations to have your ripper running properly for Audio CD`s? Should i install a Ubuntu VM and ripper on it?

**Comment by rix1337** [comment]
Nothing you we can do right now apart from finding an alternative to ripit.

You could look for potential alternatives and try them out by 

1. Installing them inside the container
2. Changing the line in ripper.sh calling ripit to the new tool


If you found something let me know.

Ripit is currently working for me, might just be the title of the cd you are testing.

**Comment by rix1337** [comment]
Please try the latest build in the **fix-ripit** branch.

It includes the updated perl script. Please verify if this solves the issue for you.

**Comment by Lobsi** [comment]
> 
> 
> Please try the latest build in the **fix-ripit** branch.
> 
> It includes the updated perl script. Please verify if this solves the issue for you.

Hi Rix, thank you for your endurance!
How is the best way to use the "fix-ripit" branch from a Unraid Server?
Does it need to target to another docker-container repository?

best regards, Lobsi

**Comment by rix1337** [comment]
Just edit the template in advanced mode and add the branch name with a colon to behind the repo links

`:fix-ripit`

**Comment by Lobsi** [comment]
Yeah, it works Rix, it works :)
I am now able to rip again, thank you very much!
The issue with the folder who is not existing is not away, but if there is no problem with that i can deal with it :)
The output of the docker-log is the following:


*** Running /etc/my_init.d/ripper.sh...
Using MakeMKV beta key: my-key-i-allready-have
19.10.2020 21:14:04 : Starting Ripper. Optical Discs will be detected and ripped within 60 seconds.
rm: cannot remove '*.tmp': No such file or directory
19.10.2020 21:14:05 : Disk tray open
19.10.2020 21:18:07 : CD detected: Saving MP3 and FLAC

**Comment by Lobsi** [comment]
OK i were to early, i tried now 6 CD`s...
the both first Discs were no problem, everything were fine and as expected.
The 4 next discs are not working anymore...
Unfortunately there is nothing i can get out of the Docker Log about the issue...

**Comment by rix1337** [comment]
Thanks for the feedback. I have merged this to the master branch. Please switch over as well, I'll delete the image from fix ripit.

That error is safe to ignore and hidden in the latest build.

Please consider a sponsorship if ripper is useful to you!

**Comment by rix1337** [comment]
The latest master build will take half an hour. If the issue persists, manually run the command from ripper.sh to see it's output. Only a specific error will be fixable

**Comment by Lobsi** [comment]
Hi Rix,
I changed back to the master Branch and got new errors, here is the error described:

Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(\\%(?:\\=)?(\w|\\{ <-- HERE (?:\w|\\[^\w\\{}]|\\\\\\[\\{}])*\\}|\\\W))/ at /usr/share/perl5/MP3/Tag.pm line 2611.
Use of uninitialized value $ENV{"USER"} in string at /usr/bin/ripit line 349.



RipIT version 4.0.0_rc_20161009.
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.

cddb: checking for os ... Linux (x86_64) [little endian] [64 bit]


Process summary:
----------------
Can't open info log file </log/autorip_>.
print() on closed filehandle SYSLOG at /usr/bin/ripit line 10172.


Please insert an audio CD!

UPDATE: I saw this is the same error i reported first, so there is something not ideal in the master branch...
Please can you put it to the master branch again? I will test it asap

regards

Lobsi

**Comment by rix1337** [comment]
If you really are using the latest version of the master image (are you?) there is nothing I can do. This is a ripit error

**Comment by rix1337** [comment]
abcde could be an alternative to ripit.

Please try manually installing it in your container and replacing the ripit command with a valid call to abcde. If it works for you I might replace ripit entirely..
