### ISSUE TITLE
Better support if using MusicBrainz instead of gnudb

### ISSUE THREAD

**Issue by kjhurley** [rix1337/docker-ripper#57]
Hi. This is a great tool and is working really well for me! Thanks for creating it.

I wanted to use MusicBrainz instead of gnudb/freedb because that database had data on a music cd I wanted to rip. However, just chaning the command line for ripit isn't enough and worse still, ripit doesn't report that it can't interpret the return from musicbrainz - it just carries on with 'unknown artist'.

For music brainz to work correctly you need to have the perl module WebService::MusicBrainz in the same location as the ripper.sh script. I simply downloaded this perl module from https://metacpan.org/pod/WebService::MusicBrainz and put it in my config folder and then modified my ripit command line and it all work.

My request is that you include WebService::MusicBrainz.pm in the docker image (in the folder with ripper.sh) as it's not obvious that if you select musicbrainz instead of gnudb it won't work!

**Comment by rix1337** [comment]
Sounds reasonable. Please make a PR that includes this change.

**Comment by rix1337** [comment]
i have taken a look at your PR
since another issue (#56) requires a custom perl module as well, might aswell install this properly.

could you please try if my installing WebService::MusicBrainz works the way I have impelemented it in the **fix-ripit** branch?

I would prefer this to adding a file to /config

**Comment by rix1337** [comment]
seems to work for the other guy at #56 
thanks for your input. ill mark this solved.
if you want, send a pr to edit the faq on how to do this!


also please consider a sponsorship if ripper is helpful to you!
