### ISSUE TITLE
Incorrect Disk Identification

### ISSUE THREAD

**Issue by Ecsport108** [rix1337/docker-ripper#6]
@rix1337 Many of my photo disks get incorrectly identified. They should show up as data disks but are seen as CDs instead resulting in a failed rip. Any way to manual override?

**Comment by rix1337** [comment]
Hi @Ecsport108,

take a look at https://github.com/rix1337/docker-ripper/blob/master/root/ripper/ripper.sh

I am using `makemkvcon -r --cache=1 info disc:9999 | grep DRV:0` to get a string ending with DRV:0,2,999,12," which for example hints at a Bluray disk.

Since I don't have access to the disk in question, you need to experiment yourself. Just modify the ripper.sh to your liking :smiley:

**Comment by rix1337** [comment]
There currently is no other way in docker (using native linux tools) to identify disk types properly.

**Comment by Ecsport108** [comment]
Thank you for your response @rix1337

I now understand that MakeMKV is being used to predict disk types, so the issue in my case is that when run by MakeMKV's identification process my disk is returning a value that leads your application to believe it is an audio CD as opposed to a data disk. 

Might I suggest adding an integer value that defaults to 0 which can be manually changed through a command when attached to the docker via command line before inserting the disk. It could have potential values of 1-4 depending on what the user enters into the command that represent BR, DVD, CD, and DATA respectively. There could be a check upon disk entry that detects when the integer does not equal 0 and skips the MakeMKV identification process entirely going straight to the ripping process using the method that matches the disk type selected by the user. The value would then be reset to 0 after completing the rip. This essentially creates a manual override that is avaliable to the user in the case of disk misidentification.

I could attempt to write this feature myself, but my CS experience is entirely Java-based and I haven't written any code in a few years. I could try and make a fork and play with it until it works...

**Comment by rix1337** [comment]
Please go ahead. Am no bash specialist myself, but this should be fairly straightforward.

**Comment by rix1337** [comment]
Closed for inactivity
