### ISSUE TITLE
CDs without metadata overwrite each other

### ISSUE THREAD

**Issue by csandman** [rix1337/docker-ripper#61]
I was trying to rip all of the CDs of an audiobook and realized about halfway through that they were overwriting each other.  Apparently there is no metadata on these disks because the folder structure ended up looking like this:

```
CD
  flac
    Unknown Artist
      Unknown Album
        01 Track 01.flac
        02 Track 02.flac
        03 Track 03.flac
      ...
  mp3
    Unknown Artist
      Unknown Album
        01 Track 01.mp3
        02 Track 02.mp3
        03 Track 03.mp3
      ...
```

Ideally there would be some kind of "folder already exists" check on the album to prevent them from overwriting each other.  I'm not sure if this is ideal for all cases, but for when the metadata isn't recognized, it would be nice if it made a new folder titled `Unknown Album_1`, `Unknown Album_2`, etc.  That way I could still bulk rip audiobooks or albums and do renaming on them afterwards based on the order I ripped them in.

**Comment by rix1337** [comment]
Thanks for the idea, which I like.

But that sounds like a lot of work for something you can easily fix by moving the folder.

For me it's a won't fix. Happy to merge a pull request that addresses this, though
