### ISSUE TITLE
Contianer always using drive /dev/sr0

### ISSUE THREAD

**Issue by GamerSocke** [rix1337/docker-ripper#62]
Hello, I am trying to use your container in Unraid with 2 Sata drives.
lsscsi -g returns these :
[0:0:0:0]    disk    SanDisk' Cruzer Fit       1.00  /dev/sda   /dev/sg0 
[1:0:0:0]    disk    USB2.0   CardReader CF    0100  /dev/sdb   /dev/sg1 
[1:0:0:1]    disk    USB2.0   CardReader SM XD 0100  /dev/sdc   /dev/sg2 
[1:0:0:2]    disk    USB2.0   CardReader MS    0100  /dev/sdd   /dev/sg3 
[1:0:0:3]    disk    USB2.0   CardReader SD    0100  /dev/sde   /dev/sg4 
**[4:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-S223C  SB04  /dev/sr0   /dev/sg5 
[6:0:0:0]    cd/dvd  HL-DT-ST BDDVDRW CH10N    1.02  /dev/sr1   /dev/sg6** 
[7:0:0:0]    disk    ATA      TOSHIBA MG07ACA1 0103  /dev/sdf   /dev/sg7 
[10:0:0:0]   disk    ATA      TOSHIBA MG07ACA1 0103  /dev/sdg   /dev/sg8 
[11:0:0:0]   disk    ATA      TOSHIBA MG07ACA1 0103  /dev/sdh   /dev/sg9 
[N:0:1:1]    disk    GIGABYTE GP-AG41TB__1                      /dev/nvme0n1  -   

I tried several configurations (these are probably the most logical, there were many more configurations):

Default configuration except changing Optical Drive to sr1

`docker run -d --name='Ripper' --net='host' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/Downloads/':'/out':'rw' -v '/mnt/user/appdata/ripper':'/config/':'rw' --device='/dev/sr1' --device=/dev/sr0:/dev/sr0 'rix1337/docker-ripper'`

changed advanced view --device parameter

`docker run -d --name='Ripper' --net='host' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/Downloads/':'/out':'rw' -v '/mnt/user/appdata/ripper':'/config/':'rw' --device='/dev/sr1' --device=/dev/sr1:/dev/sr1 --device=/dev/sg6:/dev/sg6 'rix1337/docker-ripper'`

removed Optical Drive parameter

`docker run -d --name='Ripper' --net='host' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/Downloads/':'/out':'rw' -v '/mnt/user/appdata/ripper':'/config/':'rw' --device=/dev/sr1:/dev/sr1 --device=/dev/sg6:/dev/sg6 'rix1337/docker-ripper'`

I've been trying this for at least a week now with every --device combination I can think of, and couldn't get it to rip from /dev/sr1.
The container always starts ripping from drive /dev/sr0.

Both drives are always scanned during drive detection.

I've read your "solutions" from the issues 30, 49 and 54

Unraid 6.9.1

**Comment by rix1337** [comment]
https://github.com/rix1337/docker-ripper#how-do-i-set-ripper-to-do-something-else

**Comment by rix1337** [comment]
Ripper.sh is hardcoded to /dev/sr0 - you might want to change that ;)

**Comment by GamerSocke** [comment]
Thanks for your quick reply, I think I was able to solve the problem. I replaced all DRV:0 to DRV:1 according to the log file in the directory and changed DRIVE to /dev/sr1. A note in the Readme.md would have saved me several hours. 
I had previously changed the DRIVE=/dev/sr0 to /dev/sr1 which did not solve the problem.

**Comment by rix1337** [comment]
Bro, the note is right there: https://github.com/rix1337/docker-ripper#how-do-i-set-ripper-to-do-something-else

But glad you figured it out ;)
