### ISSUE TITLE
Folder Permission Issues

### ISSUE THREAD

**Issue by pcwii** [rix1337/docker-ripper#63]
The application works as expected but whenever a directory is created for the rip storage it does not use the permission of the docker user but creates all files / folders with permission '99'
![image](https://user-images.githubusercontent.com/30759206/112694487-d6fb6d00-8e58-11eb-8270-1903272c778e.png)

**Comment by rix1337** [comment]
Sounds like an issue specific to your docker host.

Best way forward is you fix this in your local ripper.sh

I will gladly review and merge a pull request of your solution

**Comment by pcwii** [comment]
Thanks, I will have a look. I thought that I could fix it by adding the `user: 1000:1000` to the container but that only resulted in issues accessing the cd-drive
![image](https://user-images.githubusercontent.com/30759206/112698536-3f018180-8e60-11eb-9762-e80ee5d12c66.png)

**Comment by pcwii** [comment]
Changing the ripper.sh file did the trick for me. Is there a way to change/reduce the polling time for the inserted disk.

**Comment by rix1337** [comment]
Sound great! What exactly did you change? A pull request will gladly be reviewed ;)

The polling time of 60 seconds is also part of the ripper.sh (just change the `sleep 1m` line to your liking

**Comment by ghost** [comment]
it looks like the lines that have "chown -R nobody:users" could instead use variables for the user and group, so someone could just pass environment variables of USER="user" GROUP="group" when creating the container.
