### ISSUE TITLE
Completely wrong disk info?

### ISSUE THREAD

**Issue by OmgImAlexis** [rix1337/docker-ripper#65]
I just ran a few disks through and some of them are coming back with the completely wrong data, what's the process of fixing this?

**Comment by rix1337** [comment]
No idea. That's not a known issue

**Comment by OmgImAlexis** [comment]
> No idea. That's not a known issue

Have you any idea where the issue may lie? I haven’t dug into things but I’m going to take a guess that it’s getting the metadata online in ahead of from the disk?

**Comment by rix1337** [comment]
From the type of disk you are trying to rip we could try and infer the reason for your issue.

Is it data, video, audio..?

**Comment by OmgImAlexis** [comment]
It’s an audio CD. It’s also new enough that it should contain some metadata on the disk. 

It ripped all three songs fine they’re just all labeled as different CD as none of the details match.

**Comment by rix1337** [comment]
The software responsible for ripping and labeling audio is called `ripit`

you will need to create an issue there to get this resolved.
