### ISSUE TITLE
eject: unable to eject, last error: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by SimonBrooker** [rix1337/docker-ripper#68]
Using abcde.conf referenced here to rip CDs or makemkv to rip DVDs I have. I have noticed that when I put a CD in the drive, it will rip it over and over (overwriting the ripped files continuously). Checking ripper.log, I can see the following

`eject: unable to eject, last error: Inappropriate ioctl for device`
`Executing customizable pre-read function... done.`

I also tried a DVD and similar happens, re-ripping over and over, same error in ripper.log (until container is stopped or disc is manually removed). 

Any ideas?

**Comment by rix1337** [comment]
Are you running the container with the required "privileged" flag?

**Comment by SimonBrooker** [comment]
My bad, Running on unRaid ticked "Priviledged", restarted container and all seems to be well. Thanks!

**Comment by rix1337** [comment]
Glad I could help ;)
