### ISSUE TITLE
Enhancement/Feature - Parse ripper.log and makemkv, ddrescure progress to WebUI.

### ISSUE THREAD

**Issue by SimonBrooker** [rix1337/docker-ripper#69]
Would be great to have a WebUI feature that parsed information from abcde, makemkvcon & ddrescure for a more user friendly overview of ripping rather than watching mkv's get bigger in size or digging into log files.

**Comment by rix1337** [comment]
That's actually a great idea. Only web stack I know is python + flask + AngularJS.. 

I'll think about this

**Comment by rix1337** [comment]
Hi @SimonBrooker there is now a basic web UI included in the project. It will only display the log, newest entry first.

Feel free to send pull requests that improve the functionality.
