### ISSUE TITLE
Immidiate Eject

### ISSUE THREAD

**Issue by cclarke591** [rix1337/docker-ripper#7]
I have been having this issue on and off for the past little while, but recently its been every time I drop in a disk. Ripper recognizes it, but 4 seconds after ejects it, claiming it done, leaving an empty directory. Not sure how to trouble shoot this issue. Running on unraid 6.5.3.

**Comment by linxchaos** [comment]
You have to manually install the latest version of MakeMKV for some reason, at this moment to be 1.12.3. You can do that from the console window (type 'bash' first, you'll need it later) and following these instructions from the setup of this docker, ignoring the ffmpeg stuff and replacing $VERSION with 1.12.3:
[install.sh](https://github.com/rix1337/docker-ripper/blob/master/root/tmp/install/install.sh)

**Comment by rix1337** [comment]
Is MakeMKV not included in the automatic build anymore?

**Comment by rix1337** [comment]
Should be fixed now. The URL has changed. The next build should automatically install MakeMKV again
