### ISSUE TITLE
Makemkv new Version

### ISSUE THREAD

**Issue by lord-drinkalot** [rix1337/docker-ripper#75]
Hey,
trying to rip a BluRay is erroring out with the message that MakeMKV is old and needs an update.
Please trigger  a new build, thanks

**Comment by rix1337** [comment]
The ppa repo is still at 1.16.3, so you'll have to use a valid makemkv key or wait.
https://launchpad.net/~heyarje/+archive/ubuntu/makemkv-beta/+packages

**Comment by edgd1er** [comment]
@lord-drinkalot,
you may find a fork that has not this dependency over the ppa repository and the image is half the size. Wheb the ppa is updated, you will then switch back to this image.

**Comment by rix1337** [comment]
This image previously used a manual build of makemkv which took hours and resulted in an image triple the size of the current one.

No way I'll go back from PPA

**Comment by rix1337** [comment]
PPA just got the update. Latest version is now available
