### ISSUE TITLE
ripper.sh uses the wrong config file for abcde.

### ISSUE THREAD

**Issue by kjhurley** [rix1337/docker-ripper#77]
I'm trying to modify the cd ripping configuration to (a) only rip flac and (b) write in structure that is compatible with my plex folder structure (artist/album/track)

It seems

https://github.com/rix1337/docker-ripper/blob/fe0c142cca84faf52e654776089c791446a4c7a8/root/ripper/ripper.sh#L128

should use the abcde.conf file from /config folder not the one in the /ripper folder I think - see https://github.com/rix1337/docker-ripper#i-want-another-output-format-that-requires-another-piece-of-software

**Comment by rix1337** [comment]
That depends. The one at /ripper is the default one used by this project. If you want to modify abcde.conf you should indeed change that line in ripper.sh and place your custom abcde.conf at /config.

That should work. Is there any issue with this?

**Comment by kjhurley** [comment]
I guess it's a documentation thing then. The documentation seems to imply it's enough just to place a custom config file in /config/abcde.conf but it's not sufficient. You also need to edit the /config/ripper.sh script so it picks up the new file. I'm happy to create a pull request for this.

**Comment by rix1337** [comment]
Ok, I get that. What I could do is, just like with settings.conf: If there is a `abcde.conf` at /config, copy it to /ripper

We could add that at: https://github.com/rix1337/docker-ripper/blob/fe0c142cca84faf52e654776089c791446a4c7a8/root/etc/my_init.d/ripper.sh#L10

**Comment by rix1337** [comment]
I you have the time, ill gladly review/merge your PR

**Comment by rix1337** [comment]
Closed due to inactivity. Your PR is still welcome ;)
