### ISSUE TITLE
MakeMKV ignores settings.conf

### ISSUE THREAD

**Issue by veritus-maximus** [rix1337/docker-ripper#93]
Have you read and understood this [part of the readme](https://github.com/rix1337/docker-ripper#do-you-offer-support)?

[X] YES

### Issue description:

MakeMKV fails to detect/use a valid key inside Ripper. I have entered my valid, purchased registration key into a properly renamed `/config/settings.conf` and have confirmed it is copied to `/root/.MakeMKV/settings.conf` upon starting the container. However, attempting to rip any Blu-ray disc results in the following message: 

> This application version is too old. Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.

The key is valid and tested to work with MakeMKV on other platforms.

Notes:
- This is a newly registered key.
- I am running the latest Docker image on an Unraid instance

**Comment by rix1337** [comment]
@veritus-maximus  that sounds like a legit bug. I'll look into it.

First guess is the file has wrong attributes/rights set.

Have you seen: "Found settings.conf. Replacing beta key file." in your log?

This section of the startup script is responsible for handling the config:
https://github.com/rix1337/docker-ripper/blob/8b76e540658bf6fa4f52a060fe84c50a93c1a826/root/etc/my_init.d/ripper.sh#L22

Start troubleshooting with these commands:
`chown nobody:users /root/.MakeMKV/settings.conf`
`chmod 777 /root/.MakeMKV/settings.conf` (that one is overkill but might help immediately)

Restart your container afterwards and report back.

**Comment by veritus-maximus** [comment]
Thanks.

"Found settings.conf. Replacing beta key file." does appear in the logs. Unfortunately those two commands did not help.

Some more information: 
I ran into this issue after it appeared the auto-fetched beta key stopped working in Ripper, giving the same message. At the same time the current beta key (supposedly valid until 2022-04-01) stopped working on another MakeMKV instance. Resupplying the beta key worked on that other instance, as well as supplying my purchased key. Yet the issue still persists in Ripper, either from a fresh install or after supplying my registered key in `/config/settings.conf`.

**Comment by rix1337** [comment]
Hm, seems like settings.conf is ignored. No idea why

**Comment by rix1337** [comment]
What's the output of `echo $HOME` inside the container?

**Comment by veritus-maximus** [comment]
`/root` which does contain `/root/.MakeMKV/settings.conf` which was updated to hold my app key.

**Comment by rix1337** [comment]
Ok, everything was set up as expected and required by MakeMKV.

Nothing I can do without further external input.

**Comment by OmegaMann** [comment]
Hi, it seems to me that there is a bug in the makemkv. I have the same problem. I manually updated your Docker to makemkv 1.16.7 and then everything worked. I'm just relatively new to the docker game and don't really know my way around. When I rebuild Docker through my Unraid server, it always pulls version 1.16.5. Happy to help. If this all works cleanly, I'll be a supporter as well. I'm still experimenting around with unraid and docker at the moment and haven't committed yet.

**Comment by rix1337** [comment]
@OmegaMann it seems the GitHub action for pushing Releases to the Manual branch was broken. Latest commit should fix that and release a manual build of 1.16.7 within the next couple of hours.

This does not solve the issue of @veritus-maximus. But since all files were placed according to specification, I have no Idea how to get MakeMKV to get to accept your key.

**Comment by OmegaMann** [comment]
@rix1337 i will test it. With makemkvcon reg xxx you can see wich key is aktually in use and it displays me my key. Version is still old. Have i delete the docker?

**Comment by rix1337** [comment]
The build ran 12 minutes ago and should now be available.

GitHub actions should now properly build new versions again. The version check runs every 6 hours

**Comment by OmegaMann** [comment]
Thanks for that. It seems that it works. At the beginning I also had the problem that it does not want to read my key. I have now changed the file in /mnt/user/appdata/ripper and registered my key manually in the docker. No matter how, but now it notices when restarting the container that a key is deposited and takes every time my correct key. What exactly has now brought the fix - no idea.

**Comment by rix1337** [comment]
I could integrate your manual steps to register the key into this image. Could you post a guide of what commands to run?

**Comment by OmegaMann** [comment]
Of Coures. Go to the console from the docker and typ:
root@f478a3f11476:/# makemkvcon reg  xxxxxxxxxxxxxxxxxx <-- your key

Display output:
Current registration key: xxxxx
Found registration key  : xxxxx
Registration key saved.

thats it.

**Comment by rix1337** [comment]
I don't own a MakeMKV key to test this. But what you are saying it only detects the key from the file after the command? That could resolve this issue!

@veritus-maximus please run the command to verify this

**Comment by OmegaMann** [comment]
as I said, I can't say for sure. I started Docker as usual, then used your guide to fill in the file via the Unraid console and then restarted Docker. This did not work. Then I filled out the config file again via the Docker image console and also registered the key manually. From then on it worked. Unfortunately, it is no longer possible to see exactly which of the steps helped. In any case, it can't do any harm. In the worst case, you have to manually reset the key after the reboot via the command. Also not a disaster, the main thing is that it works.

**Comment by veritus-maximus** [comment]
I updated to the new manual-latest build which got things working again. I later ran `makemkvcon reg` to see if MakeMKV was actually using my key and it says it is. I never ran the command before this though so I'm assuming MakeMKV must have picked up my key from `settings.conf`.

**Comment by OmegaMann** [comment]
@veritus-maximus maybe it was because i deleted the complete docker at my place, including all persistent data. Nice that it now works for you again.

**Comment by veritus-maximus** [comment]
> I updated to the new manual-latest build which got things working again. I later ran `makemkvcon reg` to see if MakeMKV was actually using my key and it says it is. I never ran the command before this though so I'm assuming MakeMKV must have picked up my key from `settings.conf`.

Actually, I just noticed this message in my logs after starting a rip:
> "Evaluation version, 30 day(s) out of 30 remaining"

I'm not sure if this message is accurate or MakeMKV is actually using my key.

---

> @veritus-maximus maybe it was because i deleted the complete docker at my place, including all persistent data. Nice that it now works for you again.

I thought I did delete the Docker container/files and only left Ripper's `/config/` intact. I'm assuming Ripper pulled my key from the `settings.conf` there and copied it to `/root/.MakeMKV/` but I can't confirm.

**Comment by rix1337** [comment]
So from your last comments
a) this issue is resolved 
b) this issue is resolved when the `makemkvcon reg` commands is run

Which applies?

**Comment by veritus-maximus** [comment]
Can't say without further testing, but assuming (a).
