### ISSUE TITLE
DVD drive use not working in unraid.

### ISSUE THREAD

**Issue by lrdfrd** [rix1337/docker-ripper#99]
Have you read and understood this [part of the readme](https://github.com/rix1337/docker-ripper#do-you-offer-support)?

[X] YES

[] NO

### Issue description:

Not asking for support. 

Stating that this docker container on UnRaid 6.9.2, detects the drive when passed through both manually and auto bound to VFIO but has no control even when privileged. This is not functional. Dell R720.

Looks like it could be a useful project though. 
 Thank you

**Comment by rix1337** [comment]
Seems like nothing can be done.
This might be hardware-specific.
